---
title: "Mercado laboral y salarios"
output: html_document
date: "2026-03-28"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Importamos las librerías que vamos a utilizar

```{r}
library(pxR)
library(tidyverse)
library(stringr)
library(dplyr)
```

Cargamos la base de datos que vamos a utilizar

Datos de Productividad y Costes Laborales 

```{r}
url1 <- "https://www.ine.es/jaxiT3/files/t/es/px/32938.px?nocab=1"
prod<-as.data.frame(read.px(url1), stringsAsFactor=FALSE)  
names(prod)
```

Miramos los datos para filtrar. Buscamos primero los nombres de las distintas columnas.


```{r}
if ("Niveles.y.Tasas" %in% names(prod)) table(prod$Niveles.y.Tasas)
if ("Tipo.de.dato" %in% names(prod)) table(prod$Tipo.de.dato)
if ("Ratios.relevantes" %in% names(prod)) table(prod$Ratios.relevantes)
```


```{r}
prod_filtrado <- prod |>
  filter(Niveles.y.Tasas == "Variación anual") |> 
  filter(Tipo.de.dato == "Datos ajustados de estacionalidad y calendario") |>
  filter(Ratios.relevantes == "Productividad por puesto de trabajo equivalente a tiempo completo") |>
  
  mutate(ANO = as.numeric(substr(Periodo, 1, 4))) |>
  mutate(TRIM = as.numeric(substr(Periodo, 6, 7))) |>
  mutate(tiempo = ANO + TRIM * 0.25 - 0.25) |>
  
  filter(ANO >= 2008 & ANO <= 2024) |>
  
  arrange(tiempo) |>
  select(Periodo, ANO, TRIM, tiempo, value)
```

```{r}
range(prod_filtrado$ANO)
```

Datos de PIB Demanda - Volumen encadenado

```{r}
url2 <- "https://www.ine.es/jaxiT3/files/t/es/px/30678.px?nocab=1"
pib<-as.data.frame(read.px(url2), stringsAsFactor=FALSE)  
names(pib)
```

```{r}
if ("Niveles.y.tasas" %in% names(pib)) table(pib$Niveles.y.tasas)
if ("Tipo.de.dato" %in% names(pib)) table(pib$Tipo.de.dato)
if("Agregados.macroeconómicos" %in% names(pib)) table(pib$Agregados.macroeconómicos)
```

```{r}
pib_limpio <- pib |>
  filter(str_detect(Niveles.y.tasas, "Variación anual")) |> 
  filter(str_detect(Tipo.de.dato, "ajustados")) |>

  filter(str_detect(Agregados.macroeconómicos, regex("PRODUCTO", ignore_case = TRUE))) |>
  filter(str_detect(Agregados.macroeconómicos, regex("INTERIOR", ignore_case = TRUE))) |>
  filter(!str_detect(Agregados.macroeconómicos, regex("Demanda", ignore_case = TRUE))) |> 

  mutate(ANO = as.numeric(substr(Periodo, 1, 4)),
         TRIM = as.numeric(substr(Periodo, 6, 7)),
         tiempo = ANO + TRIM * 0.25 - 0.25) |>
  
  filter(ANO >= 2008 & ANO <= 2024) |>
  
  arrange(tiempo) |>

  distinct(tiempo, .keep_all = TRUE) |>
  select(Periodo, ANO, TRIM, tiempo, pib_value = value)
```


```{r}
range(pib_limpio$ANO)
```


Datos de Tasa de Paro EPA 

```{r}
url3 <- "https://www.ine.es/jaxiT3/files/t/es/px/65334.px?nocab=1"
paro<-as.data.frame(read.px(url3), stringsAsFactor=FALSE)  
names(paro)
```


```{r}
paro_limpio <- paro |>
  mutate(across(where(is.character), stringr::str_trim)) |>
  
  filter(str_detect(Comunidades.y.Ciudades.Autónomas, "Total Nacional")) |> 
  filter(Sexo == "Ambos sexos") |>
  filter(Edad == "Total") |>

  mutate(ANO = as.numeric(substr(Periodo, 1, 4)),
         TRIM = as.numeric(substr(Periodo, 6, 7)),
         tiempo = ANO + TRIM * 0.25 - 0.25) |>
  
  filter(ANO >= 2008 & ANO <= 2024) |>

  arrange(tiempo) |>
  select(Periodo, ANO, TRIM, tiempo, tasa_paro = value)

```


```{r}
range(paro_limpio$ANO)
```

Datos de Salarios

```{r}
url4 <- "https://www.ine.es/jaxiT3/files/t/es/px/6061.px?nocab=1"
salarios <- as.data.frame(read.px(url4), stringsAsFactors=FALSE)
names(salarios)
```


```{r}
salarios_limpio <- salarios |> 
  mutate(across(everything(), as.character)) |> 
  mutate(across(everything(), stringr::str_squish)) |> 
  
  rename(comp = 2, sect = 3, lug = 4) |> 
  
  filter(lug == "Total Nacional") |> 
  filter(grepl("^B_S", sect)) |> 
  filter(comp == "Coste laboral total") |> 
  
  mutate(
    salario_eur = as.numeric(value),
    ANO = as.numeric(substr(Periodo, 1, 4)),
    TRIM = as.numeric(substr(Periodo, 6, 7)),
    tiempo = ANO + TRIM * 0.25 - 0.25
  ) |> 
  
  filter(ANO >= 2008 & ANO <= 2024) |> 
  arrange(tiempo) |> 
  select(Periodo, ANO, TRIM, tiempo, salario_eur)
```

```{r}
range(salarios_limpio$ANO)
```


Unimos los data frame

```{r}

df_final <- pib_limpio |>
  inner_join(prod_filtrado, by = "tiempo") |>
  inner_join(paro_limpio, by = "tiempo") |>
  inner_join(salarios_limpio, by = "tiempo") |>
  select(
    fecha = Periodo.x, 
    tiempo, 
    pib = pib_value, 
    prod = value, 
    paro = tasa_paro,
    salario = salario_eur
  )

```

Comprobamos

```{r}
head(df_final)
```

```{r}
tail(df_final)
```

```{r}
write.csv(df_final, "base.csv", row.names = FALSE)
```





